config/routes.rb
Fids::Application.routes.draw do

  resources :belt_displays

  resources :gate_displays

  resources :counter_displays do
    get :display_results , on: :member
  end

=begin
  get "display_boards/arrivals"

  get "display_boards/departures"

  get "display_boards/arrivals_depratures"

  get "display_boards/flights"

  get "display_boards/actions"
=end

  resources :display_boards do
    get :arrivals , on: :collection
    get :departures , on: :collection
    get :arrivals_depratures , on: :collection
    get :flights , on: :collection
    get :counters , on: :collection
    get :gates , on: :collection
    get :belts , on: :collection
    get :actions , on: :collection
    get :arrival_results, on: :collection
    get :departure_results, on: :collection
    get :flight_results, on: :collection
    get :counter_results, on: :collection
    get :gate_results, on: :collection
    get :belt_results, on: :collection
    get :arrival_departure_results, on: :collection
  end

  get "displays/flights_list"
  get "user_settings/add_user"
  get "user_settings/index"
  post "user_settings/create"
  post "user_settings/delete_user"
  post "flights/delete_multiple_flights"

  resources :displays

  resources :flights

  resources :remarks

  resources :schedules

  resources :counters

  resources :belts

  resources :gates

  resources :airports

  resources :airlines

  resources :airport_details

  match 'update_status' => 'flights#update_status', via: [:put,:get]

  devise_for :users
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
  
  devise_for :users, :skip => [:registrations]                                          
    as :user do
     get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
     put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'            
  end

  root :to => 'home#index'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :airline_name, :airport_name, :available_days, :belt_number, :counter_number, :flight_number, :gate_number, :from_to, :schedule_time, :status_type, :valid_from, :valid_till, :via
	validates :airline_name, :airport_name,:flight_number,:from_to,:schedule_time,:valid_till,:valid_from,:available_days,:presence => true
	validates :flight_number, uniqueness: {message: "is already created with same date and status type", if: :check_for_type_and_date_is_present}

  def check_for_type_and_date_is_present
    Flight.where(status_type: self.status_type,flight_number: self.flight_number,schedule_date: Date.today).present?
  end
end


# @departures = Flight.where('DATE(schedule_date) = ? and  schedule_time and status_type = (?)',Date.today,"departure").page(params[:page]).per(10)
# 45.minutes.ago > schedule_time
# 45.minutes.ago < expected_time

# Time.zone = TZInfo::Timezone.get('Asia/Kolkata')
# schedule_time > 45.minutes.ago.in_time_zone
# @departures = Flight.where('DATE(schedule_date) = ? and  schedule_time.strftime("%H:%M") > ? and status_type = (?)',Date.today,45.minutes.ago.in_time_zone.strftime("%H:%M"),"departure").page(params[:page]).per(10)

# Time.parse("10:10")

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  # GET /schedules
  # GET /schedules.json
  load_and_authorize_resource
  def index
    @schedules = Schedule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schedules }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.json
  def new
    @schedule = Schedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
  end




  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(params[:schedule])
    p params
    @schedule.available_days = params[:schedule][:available_days].join(',') if params[:schedule][:available_days].present?
    @schedule.schedule_time = Time.parse(params[:schedule][:schedule_time]) if params[:schedule][:schedule_time].present?
    respond_to do |format|
      if @schedule.save
        day = params[:schedule][:available_days]
        range =  @schedule.valid_from..@schedule.valid_till
        # if range === Date.today && (day === Date.today.strftime("%A") || day.nil?)
        if range === Date.today && (day.include?(Date.today.strftime("%A")) || day.nil?)
          values = params[:schedule].except("valid_from(1i)","valid_from(2i)","valid_from(3i)","valid_till(3i)","valid_till(2i)","valid_till(1i)",:available_days)
          values[:schedule_date] = Date.today
          @flight.schedule_time = Time.parse(params[:schedule][:schedule_time]) if params[:schedule][:schedule_time].present?
          @flight =  Flight.new(values)
          if @flight.save
            format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
            format.json { render json: @schedule, status: :created, location: @schedule }
          else
            format.html { render action: "new" }
            format.json { render json: @flight.errors, status: :unprocessable_entity }
          end
        end
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render json: @schedule, status: :created, location: @schedule }
      else
        format.html { render action: "new" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        day = params[:schedule][:available_days]
        range =  @schedule.valid_from..@schedule.valid_till
        if range === Date.today && (day === Date.today.strftime("%A") || day.nil?)
          values = params[:schedule].except("valid_from(1i)","valid_from(2i)","valid_from(3i)","valid_till(3i)","valid_till(2i)","valid_till(1i)",:available_days)
          values[:schedule_date] = Date.today
          p "*******************-----------------------***********************"
          p "*******************-----------------------***********************"
          p "*******************-----------------------***********************"
          p "*******************-----------------------***********************"
          p "*******************-----------------------***********************"
          p "*******************-----------------------***********************"
          p "*******************-----------------------***********************"
          p "*******************-----------------------***********************"
          p params[:schedule][:flight_number]
          p "*******************-----------------------***********************"
          p "*******************-----------------------***********************"
          p "*******************-----------------------***********************"
          p "*******************-----------------------***********************"
          p "*******************-----------------------***********************"
          p "*******************-----------------------***********************"
          p "*******************-----------------------***********************"
          p "*******************-----------------------***********************"
          # Flight.create!(values)
          flight = Flight.find_or_initialize_by_flight_number(params[:schedule][:flight_number])
          flight.update_attributes(values)
        end
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end
end

# flight = Flight.find_or_initialize_by_flight_number(flight_number)

# flight.update_attributes(
#  street_address: street_address,
#  city_name: city_name,
#  federalid: federalid,
#  state_prov_id: state_prov_id,
#  zip_code: zip_code
# )

# flight.update_attributes(values)

# status_type: string,
# flight_number: string,
# airline_name: string,
# airport_name: string,
# via: string,
# airline_id: integer,
# from_to: string,
# schedule_date: date,
# schedule_time: time,
# actual_date: date,
# actual_time: time,
# expected_time: time,
# gate_number: string,
# counter_number: string,
# belt_number: string,
# flight_status: string


# id: 24, status_type: "arrival", flight_number: "11889",
# airline_name: "Lufthansa", airport_name: "John F. Kennedy International Airport",
# from_to: "", via: "", schedule_time: "2000-01-01 17:44:00", valid_from: "2014-10-02", 
# valid_till: "2014-10-09", available_days: "Sunday,Friday,Saturday", gate_number: "4",
# counter_number: nil, belt_number: "1", created_at: "2014-10-02 15:44:35",
# updated_at: "2014-10-09 13:42:11"


        # Schedule.all.each do |schedule|
        #   day = schedule.available_days
        #   range =  schedule.valid_from..schedule.valid_till
        #   if range === Date.today && (day === Date.today.strftime("%A") || day.nil?)
        #     p "**********/////////***********----------------+++++++++++"
        #   end
        # end

#         range =  schedule.valid_from..schedule.valid_till
#         if range === Date.today && (day === Date.today.strftime("%A") || day.nil?)

        # Schedule.all.each do |schedule|
        #   day = schedule.available_days.gsub("\n", '').gsub("-","").split(" ")
        #   range =  schedule.valid_from..schedule.valid_till
        #   if range === Date.today && (day === Date.today.strftime("%A") || day.nil?)
        #     p "**********/////////***********----------------+++++++++++"
        #     p day
        #   end
        # end

  # schedules = Hash.new
  # Schedule.all.each do |schedule|
  #   day = schedule.available_days.gsub("\n", '').gsub("-","").split(" ")
  #   p day
  #   schedules.
  #   range =  schedule.valid_from..schedule.valid_till
  #   if range === Date.today && (day === Date.today.strftime("%A") || day.nil?)
  #     p "**********/////////***********----------------+++++++++++"
  #     p day
  #   end
  # end

  # .gsub("\n", '').gsub("-","").split(" ")
  # Flight.create!(schedule)

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <div id="error_explanation">
        <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

        <ul>
        <% @schedule.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div></br>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status_type %>
    <%= f.label :status_type, "Arrival", :value => "arrival"  %>
    <%= f.radio_button :status_type, "arrival", :checked => true %>
    <%= f.label :status_type, "Departure", :value => "departure" %>
    <%= f.radio_button :status_type, "departure" %>
  </div></br>
  <div class="field">
    <%= f.label :flight_number %>
    <%= f.text_field :flight_number %>
  </div></br>
 <div class="field">
    <%= f.label :airline_name %>
    <%= f.collection_select(:airline_name, Airline.all, :airline_name, :airline_name) %>
  </div></br>
  <div class="field">
    <%= f.label :airport_name %>
    <%= f.collection_select(:airport_name, Airport.all, :airport_name, :airport_name) %>
  </div></br>
  <div class="field">
    <%= f.label :via %>
    <%= f.text_field :via %>
  </div></br>
  <div class="field">
    <%= f.label "From/To" %>
    <%= f.text_field :from_to %>
  </div></br>
  <div class="field">
    <%= f.label :schedule_time %>
    <%= f.time_select :schedule_time %>
  </div></br>
  <div class="field">
    <%= f.label :valid_from %>
    <%= f.date_select :valid_from %>
  </div></br>
  <div class="field">
    <%= f.label :valid_till %>
    <%= f.date_select :valid_till %>
  </div></br>
  <div class="field">
    <%= f.label :available_days %>
    <%#= f.text_field :available_days %>
    <%#= f.collection_check_boxes :available_days, ["M","T"] %>
    <% array = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'] %>
    <% array.each do |a_value| %>
    <%= a_value %>
     <%= f.check_box(:available_days, { :multiple => true }, a_value, nil) %>
    <% end %>
  </div></br>
  <div class="field">
    <%= f.label :gate_number %>
    <%= f.collection_select(:gate_number, Gate.all, :gate_number, :gate_number) %>
  </div></br>
  <div class="field">
    <%= f.label :counter_number %>
    <%= f.collection_select(:counter_number, Counter.all, :counter_number, :counter_number) %>
  </div></br>
  <div class="field">
    <%= f.label :belt_number %>
    <%= f.collection_select(:belt_number, Belt.all, :belt_number, :belt_number) %>
  </div></br>
  <div class="actions">
    <%= f.submit %>
  </div></br>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule,class: "btn btn-info" %> |
<%= link_to 'Back', schedules_path,class: "btn btn-info" %>

app/views/schedules/index.html.erb
<style type="text/css">
  .DisplayHeading
  {
    text-align:center;
  }
    h1
  {
    text-align:center;
  }
  table{
    font-size: 9px;
  }
</style>

<h1>Listing Schedules</h1>  
<%= link_to 'New Schedule', new_schedule_path,class:"btn btn-success" %>
</br>
<table class="table">
  <thead style="font-size:8px;">
    <tr>
      <th>Status type</th>
      <th>Flight number</th>
      <th>Airline name</th>
      <th>Airport name</th>
      <th>Via</th>
      <th>From/To</th>
      <th>Schedule time</th>
      <th>Valid from</th>
      <th>Valid till</th>
      <th>Available days</th>
      <th>Gate number</th>
      <th>Counter number</th>
      <th>Belt number</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody style="font-size:8px;">
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.status_type %></td>
        <td><%= schedule.flight_number %></td>
        <td><%= schedule.airline_name %></td>
        <td><%= schedule.airport_name %></td>
        <td><%= schedule.via %></td>
        <td><%= schedule.from_to %></td>
        <td><%= schedule.schedule_time %></td>
        <td><%= schedule.valid_from %></td>
        <td><%= schedule.valid_till %></td>
        <td><%= schedule.available_days %></td>
        <td><%= schedule.gate_number %></td>
        <td><%= schedule.counter_number %></td>
        <td><%= schedule.belt_number %></td>
        <td><%= link_to 'Show', schedule,class: "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule),class: "btn btn-info" %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
       </tr>
    <% end %>
  </tbody>
</table>
<br/>




   

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path,class: "btn btn-info" %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status type:</b>
  <%= @schedule.status_type %>
</p>

<p>
  <b>Flight number:</b>
  <%= @schedule.flight_number %>
</p>

<p>
  <b>Airline name:</b>
  <%= @schedule.airline_name %>
</p>

<p>
  <b>Airport name:</b>
  <%= @schedule.airport_name %>
</p>

<p>
  <b>Via:</b>
  <%= @schedule.via %>
</p>

<p>
  <b>From/To:</b>
  <%= @schedule.from_to %>
</p>

<p>
  <b>Schedule time:</b>
  <%= @schedule.schedule_time %>
</p>

<p>
  <b>Valid from:</b>
  <%= @schedule.valid_from %>
</p>

<p>
  <b>Valid till:</b>
  <%= @schedule.valid_till %>
</p>

<p>
  <b>Available days:</b>
  <%= @schedule.available_days %>
</p>

<p>
  <b>Gate number:</b>
  <%= @schedule.gate_number %>
</p>

<p>
  <b>Counter number:</b>
  <%= @schedule.counter_number %>
</p>

<p>
  <b>Belt number:</b>
  <%= @schedule.belt_number %>
</p>


<%= link_to 'Edit', edit_schedule_path(@schedule),class: "btn btn-info" %> |
<%= link_to 'Back', schedules_path,class: "btn btn-info" %>