config/routes.rb
Fids::Application.routes.draw do

  resources :belt_displays

  resources :gate_displays

  resources :counter_displays do
    get :display_results , on: :member
  end

=begin
  get "display_boards/arrivals"

  get "display_boards/departures"

  get "display_boards/arrivals_depratures"

  get "display_boards/flights"

  get "display_boards/actions"
=end

  resources :display_boards do
    get :arrivals , on: :collection
    get :departures , on: :collection
    get :arrivals_depratures , on: :collection
    get :flights , on: :collection
    get :counters , on: :collection
    get :gates , on: :collection
    get :belts , on: :collection
    get :actions , on: :collection
    get :arrival_results, on: :collection
    get :departure_results, on: :collection
    get :flight_results, on: :collection
    get :counter_results, on: :collection
    get :gate_results, on: :collection
    get :belt_results, on: :collection
    get :arrival_departure_results, on: :collection
  end

  get "displays/flights_list"
  get "user_settings/add_user"
  get "user_settings/index"
  post "user_settings/create"
  post "user_settings/delete_user"
  post "flights/delete_multiple_flights"

  resources :displays

  resources :flights

  resources :remarks

  resources :schedules

  resources :counters

  resources :belts

  resources :gates

  resources :airports

  resources :airlines

  resources :airport_details

  match 'update_status' => 'flights#update_status', via: [:put,:get]

  devise_for :users
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
  
  devise_for :users, :skip => [:registrations]                                          
    as :user do
     get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
     put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'            
  end

  root :to => 'home#index'

end

app/controllers/user_settings_controller.rb
class UserSettingsController < ApplicationController
  # load_and_authorize_resource
  def index
  	@users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def add_user
    @user_settings = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_setting }
    end
  end

  def show  
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @airline }
    end
  end

  def create
  	@user_settings = User.new(params[:user_settings])
    authorize! :create, @user_settings
    respond_to do |format|
      if @user_settings.save
        format.html { redirect_to user_settings_index_path, notice: 'User successfully created.' }
        format.json { render json: @user_settings, status: :created, location: @user_settings }
      else
        format.html { render action: "add_user" }
        format.json { render json: @user_settings.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete_user
    25.times do 
      p "deleting user with id"
    end
    user = User.find(params[:user])
    25.times do 
      p "deleting user with id"
    end
    respond_to do |format|
      # if (current_user == user) and (user.role == "admin")
      #   format.html { redirect_to user_settings_index_path, notice: 'You cannot delete your own account or admin.' }
      if (current_user == user)
        format.html { redirect_to user_settings_index_path, alert: 'You cannot delete your own account.' }
      elsif (user.role == "admin") 
        format.html { redirect_to user_settings_index_path, alert: 'You cannot delete admin account' }
      elsif (user.role == "user") 
        format.html { redirect_to user_settings_index_path, alert: 'You cannot delete other users account.' }
      else
        user.delete
        format.html { redirect_to user_settings_index_path, alert: 'User successfully deleted.' }
      end
    end
  end
end

app/helpers/user_settings_helper.rb
module UserSettingsHelper
end

app/views/user_settings/_new_user.html.erb
<%= form_for :user_settings,url: user_settings_create_path do |f| %>
  <% if @user_settings.errors.any? %>
		<div class="alert alert-danger alert-dismissible" role="alert">
	    <div id="error_explanation">
	      <h2><%= pluralize(@user_settings.errors.count, "error") %> prohibited this user from being Created:</h2>
	      <ul>
		      <% @user_settings.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
	      </ul>
	    </div>
    </div>
  <% end %>
  <%= f.label :email %>
  <%= f.text_field :email %><br/>

  <%= f.label :role %>
  <%= f.select(:role,["user","admin"]) %><br/>

  <%= f.label :password %>
  <%= f.text_field :password %><br/>

  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %><br/>

  <%= f.submit "Create User",class: 'btn submit' %>
<% end %>

app/views/user_settings/add_user.html.erb
<h1>New User</h1>

<%= render "new_user" %>

<%#= link_to 'Back', airlines_path %>

app/views/user_settings/index.html.erb
<style type="text/css">
#heading{
	margin-top: 10px;
	text-align: center;
	font-size: 2em;
}
</style>

<p id="heading">Users List<p>
<% if can? :create,@user %>
<%= link_to "Add New User",user_settings_add_user_path,:class => "btn btn-success" %>
<% end %>
<table class="table">
	<tr>
		<th>
		  Email
		</th>
		<th>
		  Role
		</th>
		<th>
		  Delete
		</th>
	</tr>
	<tbody style="font-size: 9px;">
  	<% @users.each do |user| %>
		<tr>
			<td><%= user.email %></td>
			<td><%= user.role %></td>
			<td><%= link_to 'Delete user', user_settings_delete_user_path(user: user), method: :post, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %></td>
		</tr>
		<% end %>
	</tbody>
</table>