config/routes.rb
Fids::Application.routes.draw do

  resources :belt_displays

  resources :gate_displays

  resources :counter_displays do
    get :display_results , on: :member
  end

=begin
  get "display_boards/arrivals"

  get "display_boards/departures"

  get "display_boards/arrivals_depratures"

  get "display_boards/flights"

  get "display_boards/actions"
=end

  resources :display_boards do
    get :arrivals , on: :collection
    get :departures , on: :collection
    get :arrivals_depratures , on: :collection
    get :flights , on: :collection
    get :counters , on: :collection
    get :gates , on: :collection
    get :belts , on: :collection
    get :actions , on: :collection
    get :arrival_results, on: :collection
    get :departure_results, on: :collection
    get :flight_results, on: :collection
    get :counter_results, on: :collection
    get :gate_results, on: :collection
    get :belt_results, on: :collection
    get :arrival_departure_results, on: :collection
  end

  get "displays/flights_list"
  get "user_settings/add_user"
  get "user_settings/index"
  post "user_settings/create"
  post "user_settings/delete_user"
  post "flights/delete_multiple_flights"

  resources :displays

  resources :flights

  resources :remarks

  resources :schedules

  resources :counters

  resources :belts

  resources :gates

  resources :airports

  resources :airlines

  resources :airport_details

  match 'update_status' => 'flights#update_status', via: [:put,:get]

  devise_for :users
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
  
  devise_for :users, :skip => [:registrations]                                          
    as :user do
     get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
     put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'            
  end

  root :to => 'home#index'

end

app/models/counter_display.rb
class CounterDisplay < ActiveRecord::Base
  attr_accessible :airline_image, :background_color, :counter_number
    mount_uploader :airline_image, AirlineLogoUploader
end

app/controllers/counter_displays_controller.rb
class CounterDisplaysController < ApplicationController
  respond_to :html, :xml, :json
  layout "displayboards", only: [:show]
  before_filter :set_counter_display, only: [:show,:edit, :update, :destroy]

  def index
    @counter_displays = CounterDisplay.all
    respond_with(@counter_displays)
  end

  def show
    respond_with(@counter_display)
  end

  def new
    @counter_display = CounterDisplay.new
    respond_with(@counter_display)
  end

  def edit
  end

  def create
    @counter_display = CounterDisplay.new(params[:counter_display])
    @counter_display.save
    respond_with(@counter_display)
  end

  def update
    @counter_display.update_attributes(params[:counter_display])
    respond_with(@counter_display)
  end

  def destroy
    @counter_display.destroy
    respond_with(@counter_display)
  end

  def display_results
    @counter_display = CounterDisplay.find(params[:id])
    respond_to do |format|
      format.js
    end
  end


  private
    def set_counter_display
      @counter_display = CounterDisplay.find(params[:id])
    end
end

app/helpers/counter_displays_helper.rb
module CounterDisplaysHelper
end

app/views/counter_displays/_display.html.erb
<style type="text/css">
    body{
        /*background-color:#00C0FF;*/
        background-color:<%= counter_display.background_color %>;
        margin-top: 35px;
        color: #000025;
        margin: hidden;
        overflow: hidden;
        /*  overflow: scroll;
        */}
    .logoImage{
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 800px;
        height: 600px;
    }
</style>

<% counter_display.background_color %>
<%= image_tag(counter_display.airline_image,class: "logoImage") %>

app/views/counter_displays/_form.html.erb
<%= form_for(@counter_display) do |f| %>
  <% if @counter_display.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@counter_display.errors.count, "error") %> prohibited this counter_display from being saved:</h2>

      <ul>
      <% @counter_display.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <br/><br/>
  <div class="field">
    <%= f.label :counter_number %>
    <%= f.number_field :counter_number %>
  </div><br/>
  <div class="field">
    <%#= f.label :airline_image %>
    <%= f.file_field :airline_image %>
  </div><br/>
  <div class="field">
    <%= f.label :background_color %>
    <%= f.text_field :background_color %>
  </div><br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/counter_displays/display_results.js.erb
$('#results').html("<%= escape_javascript(render 'display', counter_display: @counter_display)%>");

app/views/counter_displays/edit.html.erb
<h1>Editing counter_display</h1>

<%= render 'form' %>

<%= link_to 'Show', @counter_display %> |
<%= link_to 'Back', counter_displays_path %>

app/views/counter_displays/index.html.erb
<h1>Listing Counter Displays</h1>
<br/><br/>

<table class="table">
  <thead>
    <tr>
      <th>Counter number</th>
      <th>Airline image</th>
      <th>Background color</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @counter_displays.each do |counter_display| %>
      <tr>
        <td><%= counter_display.counter_number %></td>
        <td><%= counter_display.airline_image %></td>
        <td><%= counter_display.background_color %></td>
        <td><%= link_to 'Show', counter_display %></td>
        <td><%= link_to 'Edit', edit_counter_display_path(counter_display) %></td>
        <td><%= link_to 'Destroy', counter_display, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New Counter Display', new_counter_display_path, class: "btn" %>

app/views/counter_displays/new.html.erb
<h1>New Counter Display</h1>

<%= render 'form' %>

<%= link_to 'Back', counter_displays_path, class: "btn" %>

app/views/counter_displays/show.html.erb
<span id="results">
<%= render 'display', counter_display: @counter_display  %>
</span>



<script type="text/javascript">

    (function poll() {
        setTimeout(function() {
            $.ajax({
                url: "/counter_displays/<%= @counter_display.id %>/display_results",
                type: "GET",
                complete: poll,
                timeout: 2000
            })
        }, 10000);
    })();

</script>