config/routes.rb
Fids::Application.routes.draw do

  resources :belt_displays

  resources :gate_displays

  resources :counter_displays do
    get :display_results , on: :member
  end

=begin
  get "display_boards/arrivals"

  get "display_boards/departures"

  get "display_boards/arrivals_depratures"

  get "display_boards/flights"

  get "display_boards/actions"
=end

  resources :display_boards do
    get :arrivals , on: :collection
    get :departures , on: :collection
    get :arrivals_depratures , on: :collection
    get :flights , on: :collection
    get :counters , on: :collection
    get :gates , on: :collection
    get :belts , on: :collection
    get :actions , on: :collection
    get :arrival_results, on: :collection
    get :departure_results, on: :collection
    get :flight_results, on: :collection
    get :counter_results, on: :collection
    get :gate_results, on: :collection
    get :belt_results, on: :collection
    get :arrival_departure_results, on: :collection
  end

  get "displays/flights_list"
  get "user_settings/add_user"
  get "user_settings/index"
  post "user_settings/create"
  post "user_settings/delete_user"
  post "flights/delete_multiple_flights"

  resources :displays

  resources :flights

  resources :remarks

  resources :schedules

  resources :counters

  resources :belts

  resources :gates

  resources :airports

  resources :airlines

  resources :airport_details

  match 'update_status' => 'flights#update_status', via: [:put,:get]

  devise_for :users
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
  
  devise_for :users, :skip => [:registrations]                                          
    as :user do
     get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
     put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'            
  end

  root :to => 'home#index'

end

app/models/remark.rb
class Remark < ActiveRecord::Base
  attr_accessible :color, :flight_status, :local_name
 	validates :flight_status,presence: true, uniqueness: true
 	validates_format_of :flight_status,with: /[a-z]/,message: "should contain only alphabets."
end

app/controllers/remarks_controller.rb
class RemarksController < ApplicationController
  # GET /remarks
  # GET /remarks.json
  load_and_authorize_resource
  def index
    @remarks = Remark.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @remarks }
    end
  end

  # GET /remarks/1
  # GET /remarks/1.json
  def show
    @remark = Remark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @remark }
    end
  end

  # GET /remarks/new
  # GET /remarks/new.json
  def new
    @remark = Remark.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @remark }
    end
  end

  # GET /remarks/1/edit
  def edit
    @remark = Remark.find(params[:id])
  end

  # POST /remarks
  # POST /remarks.json
  def create
    @remark = Remark.new(params[:remark])

    respond_to do |format|
      if @remark.save
        format.html { redirect_to @remark, notice: 'Remark was successfully created.' }
        format.json { render json: @remark, status: :created, location: @remark }
      else
        format.html { render action: "new" }
        format.json { render json: @remark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /remarks/1
  # PUT /remarks/1.json
  def update
    @remark = Remark.find(params[:id])

    respond_to do |format|
      if @remark.update_attributes(params[:remark])
        format.html { redirect_to @remark, notice: 'Remark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @remark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /remarks/1
  # DELETE /remarks/1.json
  def destroy
    @remark = Remark.find(params[:id])
    @remark.destroy

    respond_to do |format|
      format.html { redirect_to remarks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/remarks_helper.rb
module RemarksHelper
end

app/views/remarks/_form.html.erb
<%= form_for(@remark) do |f| %>
  <% if @remark.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <div id="error_explanation">
        <h2><%= pluralize(@remark.errors.count, "error") %> prohibited this remark from being saved:</h2>

        <ul>
        <% @remark.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :flight_status %>
    <%= f.text_field :flight_status %>
  </div></br>
  <div class="field">
    <%= f.label :local_name %>
    <%= f.text_field :local_name %>
  </div></br>
  <div class="field">
    <%= f.label :color %>
    <%= f.select(:color,["AliceBlue", "AntiqueWhite", "Aqua", "Aquamarine", "Azure", "Beige", "Bisque", "Black", "BlanchedAlmond", "Blue", "BlueViolet", "Brown", "BurlyWood", "CadetBlue", "Chartreuse", "Chocolate", "Coral", "CornflowerBlue", "Cornsilk", "Crimson", "Cyan", "DarkBlue", "DarkCyan", "DarkGoldenRod", "DarkGray", "DarkGreen", "DarkKhaki", "DarkMagenta", "DarkOliveGreen", "DarkOrange", "DarkOrchid", "DarkRed", "DarkSalmon", "DarkSeaGreen", "DarkSlateBlue", "DarkSlateGray", "DarkTurquoise", "DarkViolet", "DeepPink", "DeepSkyBlue", "DimGray", "DodgerBlue", "FireBrick", "FloralWhite", "ForestGreen", "Fuchsia", "Gainsboro", "GhostWhite", "Gold", "GoldenRod", "Gray", "Green", "GreenYellow", "HoneyDew", "HotPink", "Indigo", "Ivory", "Khaki", "Lavender", "LavenderBlush", "LawnGreen", "LemonChiffon", "LightBlue", "LightCoral", "LightCyan", "LightGoldenRodYellow", "LightGray", "LightGreen", "LightPink", "LightSalmon", "LightSeaGreen", "LightSkyBlue", "LightSlateGray", "LightSteelBlue", "LightYellow", "Lime", "LimeGreen", "Linen", "Magenta", "Maroon", "MediumAquaMarine", "MediumBlue", "MediumOrchid", "MediumPurple", "MediumSeaGreen", "MediumSlateBlue", "MediumSpringGreen", "MediumTurquoise", "MediumVioletRed", "MidnightBlue", "MintCream", "MistyRose", "Moccasin", "NavajoWhite", "Navy", "OldLace", "Olive", "OliveDrab", "Orange", "OrangeRed", "Orchid", "PaleGoldenRod", "PaleGreen", "PaleTurquoise", "PaleVioletRed", "PapayaWhip", "PeachPuff", "Peru", "Pink", "Plum", "PowderBlue", "Purple", "Red", "RosyBrown", "RoyalBlue", "SaddleBrown", "Salmon", "SandyBrown", "SeaGreen", "SeaShell", "Sienna", "Silver", "SkyBlue", "SlateBlue", "SlateGray", "Snow", "SpringGreen", "SteelBlue", "Tan", "Teal", "Thistle", "Tomato", "Turquoise", "Violet", "Wheat", "White", "WhiteSmoke", "Yellow", "YellowGreen"]) %>
  </div></br>
  <div class="actions">
    <%= f.submit %>
  </div></br>
<% end %>

app/views/remarks/edit.html.erb
<h1>Editing remark</h1>

<%= render 'form' %>

<%= link_to 'Show', @remark,class: "btn btn-info" %> |
<%= link_to 'Back', remarks_path,class: "btn btn-info" %>

app/views/remarks/index.html.erb
<h1 style="text-align:center;">Listing remarks</h1>
<%= link_to 'New Remark', new_remark_path,class:"btn btn-success" %>
<br><br>

<table class="table">
  <tr>
    <th>Flight status</th>
    <th>Local name</th>
    <th>Color</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <tbody style="font-size:10px;">
    <% @remarks.each do |remark| %>
      <tr>
        <td><%= remark.flight_status %></td>
        <td><%= remark.local_name %></td>
        <td><%= remark.color %></td>
        <td><%= link_to 'Show', remark,class:"btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_remark_path(remark),class:"btn btn-info" %></td>
        <td><%= link_to 'Destroy', remark,method: :delete,data: {confirm: 'Are you sure?'},class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>

app/views/remarks/new.html.erb
<h1>New remark</h1>

<%= render 'form' %>

<%= link_to 'Back', remarks_path,class: "btn btn-info" %>

app/views/remarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Flight status:</b>
  <%= @remark.flight_status %>
</p>

<p>
  <b>Local name:</b>
  <%= @remark.local_name %>
</p>

<p>
  <b>Color:</b>
  <%= @remark.color %>
</p>


<%= link_to 'Edit', edit_remark_path(@remark),class: "btn btn-info" %> |
<%= link_to 'Back', remarks_path,class: "btn btn-info" %>